services:
  db:
    image: postgres:16
    container_name: eggnog_pg
    restart: always
    environment:
      POSTGRES_USER: eggnog
      POSTGRES_PASSWORD: password
      POSTGRES_DB: eggnogdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d

  web:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    container_name: streamlit_app
    ports:
      - "8501:8501"
    depends_on:
      - db
    volumes:
      - .:/app
    environment:
      - DB_HOST=db
      - DB_NAME=eggnogdb
      - DB_USER=eggnog
      - DB_PASSWORD=password

volumes:
  pgdata:
