CREATE TABLE eggnog_annotations (
    id SERIAL PRIMARY KEY,
    query_id TEXT NOT NULL,
    seed_ortholog TEXT,
    evalue DOUBLE PRECISION,
    score DOUBLE PRECISION,
    eggnog_ogs TEXT,
    max_annot_lvl TEXT,
    cog_category TEXT,
    description TEXT,
    preferred_name TEXT,
    gos TEXT,
    ec TEXT,
    kegg_ko TEXT,
    kegg_pathway TEXT,
    kegg_module TEXT,
    kegg_reaction TEXT,
    kegg_rclass TEXT,
    brite TEXT,
    kegg_tc TEXT,
    cazy TEXT,
    bigg_reaction TEXT,
    pfams TEXT
);
